### ISSUE TITLE
No 1.19.4 Release

### ISSUE THREAD

**Issue by ChecksumDev** [jrbudda/Vivecraft_Spigot_Extensions#100]
I noticed the commit for 1.19.4 support and was wondering if it was not ready as its release is not published as of yet.
https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases/tag/1.19r1

**Comment by untuned** [comment]
Duplicate of https://github.com/jrbudda/Vivecraft_Spigot_Extensions/issues/99

**Comment by jrbudda** [comment]
nobody has reported any bugs so I've uploaded it here to the 1.19 release
