### ISSUE TITLE
[Suggestion/Request] Button presses

### ISSUE THREAD

**Issue by JavaIsHot** [jrbudda/Vivecraft_Spigot_Extensions#110]
My use of github is a rare occurrence.

I'm no good programmer, but I try, and currently I am trying to make a cool VR project for myself to play.
The thing is, I'm very limited with just head and hands tracking, so if it'd be possible to incorporate button presses, it would be VERY much appreciated.

I'm sorry if this isn't the right way to use github issues, or just github in general. I tried to google where to suggest/request a feature, and didn't really get good results.

Thanks.

**Comment by fayer3** [comment]
if you need client button presses, you likely want to create a mod, not a server plugin.
server only gets attack and use info afaik, and that is vanilla

**Comment by JavaIsHot** [comment]
Aw man. Alright, thanks for telling me
