### ISSUE TITLE
[Request] Add VSE to spigot website.

### ISSUE THREAD

**Issue by cuddlebunny1996** [jrbudda/Vivecraft_Spigot_Extensions#17]
hi   my surver pervider will not add your plugin to the plugin list becuse it not on the bickkit or spigot resources page   do you think you can put it up on that ples  it will a lot of server perviders to put it on ther install list to allow ther users to add it to ther server and i want to make all my surver users happy

**Comment by jrbudda** [comment]
https://www.spigotmc.org/resources/vivecraft-spigot-extensions.33166/
