### ISSUE TITLE
Spigot extension does not send arm & head data

### ISSUE THREAD

**Issue by AlbertMN** [jrbudda/Vivecraft_Spigot_Extensions#18]
Hey there. I just installed the Spigot extension, and it doesn't seem to be working, can't see why. On regular Minecraft, other players can't see me swing my arms or anything, my head just spazzes' out :/

I am running Spigot 1.10.2.

Thank you in advance.

**Comment by jrbudda** [comment]
Are the other users using Vivecraft? it only works if you have a client-side mod

**Comment by AlbertMN** [comment]
I didn't know that. I thought everyone should be able to see the arm-data - would've been nice :)
Thanks for clarifying!
