### ISSUE TITLE
"Player moved wrongly" when teleporting

### ISSUE THREAD

**Issue by Azzurite** [jrbudda/Vivecraft_Spigot_Extensions#33]
I'm using a Vive, Minecraft 1.11.2, the release "Vivecraft Spigot Extensions v5" and "latest" Spigot version from around 10.01.2017 (whatever that is, I don't know how to find out). There are no additional plugins installed.

The only configuration changes I did were in server.properties. I also changed the "moved-wrongly-threshold" in spigot.yml to a very high value after noticing this problem.

The problem is that sometimes, when I teleport on my server, I get teleported back and the server prints the message "[Player] moved wrongly".
I'm not absolutely sure when it happens, but it seems to have to do something with distance and/or obstruction of the path to the destination.
For example, I notice this behaviour when I'm near trees and try to teleport around leaves of the trees. It happens quite frequently around fences, too. Sometimes I'm able to teleport "through" fences, sometimes not. But it also happens in simple mineshafts, mostly near corners.

The behaviour is very inconsistent but definitely noticeable. Sometimes I only need to move the teleport location a quarter of a block and it works.

I tried looking in the source code of this project and the Vivecraft project itself, and noticed that the "moved-wrongly-threshold" is automatically set to 10. 
Since I am a developer myself, I downloaded the source and changed the value from 10 to 10000000. This seems to have fixed the problem. (btw, it's a bit hard to set up this project, I had to wing it pretty hard ;)

Maybe one or any of these should be considered:
- setting moved-wrongly-threshold to a bigger value
- only increasing moved-wrongly-threshold to a higher value when it was configured to be lower, not when the server already has a very large moved-wrongly-threshold (and I wondered why my changing of moved-wrongly-threshold had no effect!)
- adding a configuration option to enable /tp even when VSE is installed
- and of course some other fix for this which I can't think of

**Comment by Azzurite** [comment]
Fixed with newest update.

**Comment by jrbudda** [comment]
Ah thanks for following up. Just note that this requires updated clients too.
