### ISSUE TITLE
Permissions Never Set?

### ISSUE THREAD

**Issue by ALEXTHENINJA007** [jrbudda/Vivecraft_Spigot_Extensions#36]
Vivecraft_Spigot_Extensions-9-
In VSE,java you have _public void setPermissionsGroup(Player p)_ 
However as far as I could find its never called, and thus no permissions exist for vivecraft at all.

BackStory:
Im using vivecraft on a server but with anticheat plugins, so im overriding some of there violation events, and wanted to use permissions to override them if they were a vive player and thus has "vive.viveplayer" as a permission.

**Comment by jrbudda** [comment]
uhh whoops.

[Vivecraft_Spigot_Extensions.zip](https://github.com/jrbudda/Vivecraft_Spigot_Extensions/files/1538868/Vivecraft_Spigot_Extensions.zip)

Also I looked at PAC and it has a permissions bypass system so i dunno why you need to write anything, just add Phoenix.Bypass.<module_name> to the vive group using vault.

**Comment by ALEXTHENINJA007** [comment]
Thanks, 
Vault is the plugin I assume? I might use Vault, however I its doc links a broken and its probably a little overkill to have it just for that. I might just look at your code again and schedule to check if they are a vive player and give them the Phoenix.Bypass.<module_name> permission.
