### ISSUE TITLE
bungee

### ISSUE THREAD

**Issue by Redd56** [jrbudda/Vivecraft_Spigot_Extensions#43]
bungee cord support?... also i should probably move that question here and not on the client git repo lol

**Comment by Redd56** [comment]
Still nothing? Please?

**Comment by Phoenix616** [comment]
How exactly would bungee support look like? As far as I understand the goal of this plugin is to improve movement on the server and forward data to other users. Nothing that would interact with Bungee in any way.

**Comment by jrbudda** [comment]
Hey we did this one
