### ISSUE TITLE
Vault?

### ISSUE THREAD

**Issue by nzjfun** [jrbudda/Vivecraft_Spigot_Extensions#58]
Error in console:
[Vivecraft] Vault not found, permissions groups will not be set

I have no clue what to do. Please help.

**Comment by Espergium** [comment]
It means exactly what it says. The Vault plugin was not found, therefore you won't have a permissions group.

**Comment by Techjar** [comment]
Yeah it's just a warning. If you aren't using permissions it doesn't matter.

**Comment by nzjfun** [comment]
Define permissions. I may be using them.

**Comment by nzjfun** [comment]
Nevermind. Solved it.
