### ISSUE TITLE
1.15 support?

### ISSUE THREAD

**Issue by Legoman99573** [jrbudda/Vivecraft_Spigot_Extensions#60]
Not really a bug, but wonder if this mod will work with 1.15 compatability since it released yesterday as of posting this?

**Comment by TheTrueForce** [comment]
Don't you think it's a bit early to be asking this question?

**Comment by Legoman99573** [comment]
@TheTrueForce it is, but might as well post it before someone else asks it.

**Comment by ZwipZwapZapony** [comment]
What point is there to update the Vivecraft Spigot Extensions plug-in for Minecraft 1.15 if Vivecraft, which is what the plug-in is for, is not available for Minecraft 1.15 yet?

(And Vivecraft for 1.15 will have to wait until OptiFine for 1.15 becomes available, and that's not available yet either.)

**Comment by electronstudio** [comment]
The point is that you can use OptiFine/Vivecraft 1.14 to play on a 1.15 server via ProtocolSupport plugin.

**Comment by Espergium** [comment]
Optifine still isn't ready and it's only being built for 1.15.1 right now.

**Comment by electronstudio** [comment]
Optifine works fine on 1.14 with a 1.15 server, I am playing it right now.

**Comment by Espergium** [comment]
To not mislead people further: you are using a 1.14 client on a server side plugin that allows version mismatching.

However this is a thread asking for 1.15 support of the **vivecraft client** which I just said is not possible due to optifine still being built.

**Comment by electronstudio** [comment]
This thread is asking for the server extensions, it has nothing to do with the client.
