### ISSUE TITLE
Creepers won't attack on server version 1.15.2

### ISSUE THREAD

**Issue by lallenlowe** [jrbudda/Vivecraft_Spigot_Extensions#63]
All other mobs attack, but Creepers just sit there looking at you. I tried setting CreeperRadius to false, but that didn't change anything. Let me know if you need any other information from me.

**Comment by jrbudda** [comment]
ya any errors in the log? the damn creepers and endermen always break every update...

**Comment by lallenlowe** [comment]
Let me look

**Comment by lallenlowe** [comment]
@jrbudda hm, I don't see errors in the logs

**Comment by lallenlowe** [comment]
If I enable debug in server.properties could that be helpful?

**Comment by jrbudda** [comment]
we've reproduced the issue on the test server. sit tight and thank you for bringing it to our attention.

**Comment by jrbudda** [comment]
should be fixed in r3, if you could please verify.

**Comment by lallenlowe** [comment]
Fixed in r3, verified. THANKS!
