### ISSUE TITLE
Add option to disable the horse jump thing

### ISSUE THREAD

**Issue by JasonHorkles** [jrbudda/Vivecraft_Spigot_Extensions#66]
Many anti-cheats don't like when people have the horse auto jump enabled so it'd be nice to have an option to just disable that entirely so there aren't issues with that

**Comment by Techjar** [comment]
Isn't that a vanilla feature tho?

**Comment by Techjar** [comment]
If some servers really are throwing a fit over horses walking up ledges, then the server owners have configured it wrong. It's a vanilla feature and as such everyone will be affected by it.

**Comment by JasonHorkles** [comment]
I mean like the locomotion thing where you teleport up blocks to prevent motion sickness

**Comment by Techjar** [comment]
Oh so the while not on horses thing. There's already an option for that, called "Walk Up Blocks" or something like that.

**Comment by JasonHorkles** [comment]
In the VSE config? Because I don't see it

**Comment by Techjar** [comment]
No it's a client setting.

**Comment by JasonHorkles** [comment]
That's why I'm wanting there to be an option to disable it server-wide, then they don't have to go into their settings and figure out how to disable it haha

**Comment by Techjar** [comment]
Seems like a rather minor thing. Couldn't you just disable this specific anti-cheat for VR players?

**Comment by JasonHorkles** [comment]
If I can figure out how the permission thing works regarding it then yeah

**Comment by Techjar** [comment]
You just need to have Vault installed and then assign permissions to group name set in the VSE config.

**Comment by JasonHorkles** [comment]
I have LuckPerms but I'm not sure how all that works. Do I make a group called a specific thing or just give the vivecraft perm node to that group?

**Comment by Techjar** [comment]
VSE adds VR players to the group in its config, so you just give the permissions to that group.

**Comment by JasonHorkles** [comment]
Alright. If I can't figure it out I'll ask in the Discord server
Thanks

**Comment by Techjar** [comment]
We know some permissions plugins have problems with automatically assigned groups via the Vault API, but to my knowledge LuckPerms handles it correctly.
