### ISSUE TITLE
Does this work with PaperMC

### ISSUE THREAD

**Issue by QPCrummer** [jrbudda/Vivecraft_Spigot_Extensions#74]
I was wondering if it worked with PaperMC. I thought Spigot and Paper were the same, just paper had more performance improvements. I am currently using a server type called YatopiaMC (https://github.com/YatopiaMC/Yatopia). Could you also tell me if it would work with Yatopia, thanks!

**Comment by QPCrummer** [comment]
I got it to work, but when I do /plugin , it shows up red. Is that normal?

**Comment by TheCreeperCow** [comment]
If its red that means it encountered a critical error during startup please review the logs/console for any errors and post them here

**Comment by QPCrummer** [comment]
I don’t use PaperMC anymore. I use a fabric server.
