### ISSUE TITLE
Color Portals plugin does not work in VR mode

### ISSUE THREAD

**Issue by belleDESiRE** [jrbudda/Vivecraft_Spigot_Extensions#75]
Hi,

Yesterday got my Oculus Quest 2 headset, installed vivecraft on my client pc and 1.16.3 spigot server.
First off: WOW, what a great plugin is vivecraft!

The only issue I have is that a plugin that works for normal/non vr users does not work when in vivecraft:
https://www.spigotmc.org/resources/color-portals.5546/

It basically is a teleport plugin that allows users to build a wool portal consisting of a button and a pressure plate, when they stand on the pressure plate and press the button they tp to another portal.
I see no error logs, warnings or anything deviating at all in the server logs it just does not work (I do hear the sound related to the button press).

Any idea?

**Comment by Techjar** [comment]
That's uh... weird. Not really sure how we'd be breaking a server-side plugin like that.

**Comment by TheCreeperCow** [comment]
Please contact the plugin author and make sure there are no errors without errors this is gonna be very difficult to figure out

**Comment by belleDESiRE** [comment]
Ok, will ask. Will let you know if and/or whenever something is found there

**Comment by belleDESiRE** [comment]
Well, the color portals plugin developer does not seem to respond anymore, we did some troubleshooting (other teleporting plugins do work in vr). But since then no more replies.

So I guess nothing I can do but close this case as it seems to be not a vivecraft issue
