### ISSUE TITLE
java.lang.IllegalArgumentException: Could not determine java version from '11.0.9.1'.

### ISSUE THREAD

**Issue by YungSamzy** [jrbudda/Vivecraft_Spigot_Extensions#78]
Hey! I'm new to java and I'm trying to compile this. It keeps popping up with this? Can you help me?

**Comment by YungSamzy** [comment]
Fixed. The wrapper was outdated.

**Comment by blackfoxxx** [comment]
hello , 
can you share your discord please or any other app , i have a project need to discuss with you
