### ISSUE TITLE
java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.world.entity.player.EntityHuman.fz()

### ISSUE THREAD

**Issue by CorneliusCornbread** [jrbudda/Vivecraft_Spigot_Extensions#90]
On join I receive this error
```
[Fri 20:12:33 INFO  Server/PlayerConnection] GaymerCornelius lost connection: Internal Exception: java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.world.entity.player.EntityHuman.fz()'
```

Paper: 1.19.1-91
Plugin: 1.19r1
Plugins: (all latest version as of writing)
- DiscordSRV
- Floodgate
- Geyser
- NerfPhantoms
- ServerBackup
- Spark
- TradeSystem
- ViaBackwards (4.4.1)
- ViaVersion (4.4.1)
- Voicechat-bukkit
- NoEncryption (no disabling this does not solve the disconnect issues)

**Comment by Techjar** [comment]
The plugin is for 1.19.0, no 1.19.1 support yet.

**Comment by jrbudda** [comment]
updated
