### ISSUE TITLE
No 1.19.4 Jar File

### ISSUE THREAD

**Issue by untuned** [jrbudda/Vivecraft_Spigot_Extensions#99]
This was committed (https://github.com/jrbudda/Vivecraft_Spigot_Extensions/commit/c73fab07144fdc150fba006536e82f6ddf00d8a6), but the jar file was not built and added to the release.

**Comment by fayer3** [comment]
the jar file is available in the discord #testing channel, since it's still in the testing phase

**Comment by jrbudda** [comment]
nobody has reported any bugs so I've uploaded it here to the 1.19 release
